[[redirects]]
  from = "/api/signup"
  to = "https://basic-mern-authentication.herokuapp.com/signup"
  status = 200
  force = true

[[redirects]]
  from = "/api/login"
  to = "https://basic-mern-authentication.herokuapp.com/login"
  status = 200
  force = true

[[redirects]]
  from = "/api/user"
  to = "https://basic-mern-authentication.herokuapp.com/user"
  status = 200
  force = true

[[redirects]]
  from = "/api/logout"
  to = "https://basic-mern-authentication.herokuapp.com/logout"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
